version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV=${ENV}
      - LOG_LEVEL=
    command: go run main.go

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}