version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - 

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=apigateway,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4571:4571"  # API Gateway mock port
    volumes:
      - "./localstack:/tmp/localstack"
