version: '3.8'

services:
  auth-service:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - .:/app
    environment:
      - ENV=${ENV}
      - LOG_LEVEL=
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}